<?php
/**
 * @file
 * Defines simple camera src
 */

/**
 * Implements hook_theme().
 */

function camera_widget_theme() {

    $theme = [];
    $theme['camera'] = [
      'render element' => 'element',
      'template' => 'camera',
      'variables' => [
        'canvas_id' => '',
        'camera_src' => '',
        'width' => 100,
        'height' => 40,
        'settings' => [],
        'attributes' => []
      ],
    ];
    return $theme;
  }
  